import type { Concert } from "@/domain/artists/concerts/types"

function seconds(timestamp: string): number {
  return timestamp
    .split(":")
    .map(Number)
    .reduce((total, part) => total * 60 + part, 0)
}

export const concerts: readonly Concert[] = [
  {
    id: "david-guetta-monolith-alula",
    artistId: "david-guetta",
    title: "The Monolith at AlUla",
    eventName: "The Monolith",
    recordedOn: "2023-12",
    dateLabel: "December 2023",
    venue: {
      name: "The AlUla desert",
      city: "AlUla",
      country: "Saudi Arabia",
    },
    durationSeconds: 3353,
    source: {
      platform: "youtube",
      videoId: "M6tLJTwcp1g",
      originalUrl: "https://youtu.be/M6tLJTwcp1g?si=FzLKG2upqlmEi1nU",
      uploader: "David Guetta",
    },
    description:
      "A one-hour audiovisual performance staged against AlUla's monumental desert landscape.",
    featured: true,
    setlist: [
      { title: "Intro", startAtSeconds: seconds("00:00") },
      {
        title:
          "Mystery & Mist vs Mental Obsession vs With or Without You (David Guetta & DJs From Mars Mashup)",
        startAtSeconds: seconds("01:00"),
      },
      {
        title: "Luminous vs Sexy Boy vs Blue Monday (David Guetta & DJs From Mars Mashup)",
        startAtSeconds: seconds("03:49"),
      },
      {
        title: "Don't You Know vs What Else Is There? (David Guetta & DJs From Mars Mashup)",
        startAtSeconds: seconds("07:37"),
      },
      { title: "The Truth — David Guetta & MORTEN", startAtSeconds: seconds("09:54") },
      { title: "Relax (David Guetta Rework) — Frankie Goes to Hollywood", startAtSeconds: seconds("12:35") },
      { title: "We Are the People (Adam Sellouk Remix / MORTEN Edit)", startAtSeconds: seconds("15:52") },
      { title: "Solitude (Hypaton Rework) — M83", startAtSeconds: seconds("19:26") },
      { title: "The Final Countdown (Hypaton & David Guetta Remix)", startAtSeconds: seconds("21:28") },
      { title: "Rej vs Joga (David Guetta & DJs From Mars Mashup)", startAtSeconds: seconds("24:42") },
      { title: "Can You Feel It — MORTEN", startAtSeconds: seconds("27:36") },
      { title: "Syren vs Rush vs Somebody That I Used to Know", startAtSeconds: seconds("29:00") },
      { title: "Rave Is the Future vs Shout", startAtSeconds: seconds("32:00") },
      { title: "Eternity vs Enjoy the Silence", startAtSeconds: seconds("34:03") },
      { title: "Aria — Argy & Omnya", startAtSeconds: seconds("36:20") },
      { title: "Consciousness vs It's a Fine Day", startAtSeconds: seconds("39:04") },
      { title: "Alive Again / My House / In My Mind / Night After Night / Runaway", startAtSeconds: seconds("41:55") },
      { title: "Solar / Juno / Rapture", startAtSeconds: seconds("46:43") },
      { title: "The Future Is Now — David Guetta & MORTEN", startAtSeconds: seconds("49:11") },
      { title: "Titanium (Future Rave Remix) — David Guetta feat. Sia", startAtSeconds: seconds("52:28") },
    ],
  },
  {
    id: "david-guetta-nye-louvre-abu-dhabi",
    artistId: "david-guetta",
    title: "NYE Livestream from Louvre Abu Dhabi",
    eventName: "New Year's Eve at Louvre Abu Dhabi",
    recordedOn: "2021-12-31",
    dateLabel: "December 31, 2021",
    venue: {
      name: "Louvre Abu Dhabi",
      city: "Abu Dhabi",
      country: "United Arab Emirates",
    },
    durationSeconds: 3767,
    source: {
      platform: "youtube",
      videoId: "iIn5uuGbmMU",
      originalUrl: "https://www.youtube.com/live/iIn5uuGbmMU?si=TcjD_iHyL2KScfNN",
      uploader: "David Guetta",
    },
    description:
      "A New Year's Eve livestream performed from a custom-built stage overlooking the Persian Gulf at Louvre Abu Dhabi.",
    setlist: [
      { title: "Intro", startAtSeconds: seconds("00:00") },
      { title: "Fabrication — Hot Foot", startAtSeconds: seconds("05:11") },
      { title: "Titanium (David Guetta & MORTEN Future Rave Remix)", startAtSeconds: seconds("07:13") },
      { title: "Love Tonight (David Guetta Remix) — SHOUSE", startAtSeconds: seconds("11:56") },
      { title: "Moth To a Flame — Swedish House Mafia & The Weeknd (Remix)", startAtSeconds: seconds("14:50") },
      { title: "Pink Soldiers vs Do It To It (Bootleg)", startAtSeconds: seconds("17:24") },
      { title: "It Gets Better (Guetta & Zedd Edit) — Swedish House Mafia", startAtSeconds: seconds("20:25") },
      { title: "Silver Screen (Shower Scene) — David Guetta x Felix Da Housecat x Miss Kittin", startAtSeconds: seconds("22:40") },
      { title: "Permanence — David Guetta & MORTEN", startAtSeconds: seconds("25:36") },
      { title: "God Is a DJ — Faithless vs David Guetta", startAtSeconds: seconds("28:34") },
      { title: "Rapture — iiO feat. Nadia Ali (David Guetta Remix)", startAtSeconds: seconds("31:49") },
      { title: "How Do You Feel — MORTEN", startAtSeconds: seconds("34:06") },
      { title: "Supercycle — Jack Back x Citizen Kain x Kiko", startAtSeconds: seconds("36:13") },
      { title: "Alive Again — David Guetta x MORTEN x Roland Clark", startAtSeconds: seconds("40:21") },
      { title: "Play Hard (Rocas Edit) — David Guetta feat. Ne-Yo & Akon", startAtSeconds: seconds("44:27") },
      { title: "My Universe (David Guetta Remix) — Coldplay x BTS", startAtSeconds: seconds("46:45") },
      { title: "Driver's Licence On My Knees (Bootleg) — RÜFÜS DU SOL vs Olivia Rodrigo", startAtSeconds: seconds("48:27") },
      { title: "Café del Mar (David Guetta Rework) — Energy 52", startAtSeconds: seconds("50:56") },
      { title: "When Love Takes Over (Future Rave Remix)", startAtSeconds: seconds("55:00") },
      { title: "Sexy Bitch (Techy Remix) — David Guetta feat. Akon", startAtSeconds: seconds("57:28") },
      { title: "End Credits", startAtSeconds: seconds("1:01:23") },
    ],
  },
  {
    id: "david-guetta-united-at-home-dubai",
    artistId: "david-guetta",
    title: "United at Home — Dubai Edition",
    eventName: "United at Home",
    recordedOn: "2021-02-06",
    dateLabel: "February 6, 2021",
    venue: {
      name: "Burj Al Arab helipad",
      city: "Dubai",
      country: "United Arab Emirates",
    },
    durationSeconds: 3906,
    source: {
      platform: "youtube",
      videoId: "xaurMcGqZHU",
      originalUrl: "https://www.youtube.com/live/xaurMcGqZHU?si=iCg6L7LPf9dPczim",
      uploader: "David Guetta",
    },
    description:
      "A sunset charity broadcast from the Burj Al Arab helipad, 210 metres above Dubai.",
    setlist: [
      { title: "Intro", startAtSeconds: seconds("00:00") },
      { title: "Titanium (Future Rave Remix)", startAtSeconds: seconds("02:25") },
      { title: "Witching Hour (David Guetta Rework)", startAtSeconds: seconds("07:15") },
      { title: "Play Hard (Future Rave Remix)", startAtSeconds: seconds("10:05") },
      { title: "Let's Love (Future Rave Remix)", startAtSeconds: seconds("13:18") },
      { title: "Air — David Guetta & MORTEN", startAtSeconds: seconds("16:10") },
      { title: "Dreams — David Guetta & MORTEN feat. Lanie Gardner", startAtSeconds: seconds("19:47") },
      { title: "Amsterdam — Jack Back", startAtSeconds: seconds("23:32") },
      { title: "Love Is Gone (2020 Remix)", startAtSeconds: seconds("27:05") },
      { title: "You Can't Change Me", startAtSeconds: seconds("29:30") },
      { title: "Permanence — Jack Back", startAtSeconds: seconds("34:45") },
      { title: "Domino (2021 David Guetta Remix) — Oxia", startAtSeconds: seconds("38:50") },
      { title: "Memories (2021 Remix)", startAtSeconds: seconds("41:20") },
      { title: "Sexy Bitch (David Guetta Techy Remix)", startAtSeconds: seconds("45:00") },
      { title: "Spectrum (Say My Name) (David Guetta Remix)", startAtSeconds: seconds("48:34") },
      { title: "When Love Takes Over (Future Rave Remix)", startAtSeconds: seconds("51:56") },
      { title: "Odyssey — David Guetta & MORTEN", startAtSeconds: seconds("55:00") },
      { title: "Café del Mar (Tale of Us Renaissance Remix)", startAtSeconds: seconds("59:37") },
      { title: "Outro", startAtSeconds: seconds("1:03:30") },
    ],
  },
  {
    id: "hans-zimmer-diamond-in-the-desert-compilation",
    artistId: "hans-zimmer",
    title: "Live in Concert — The Ultimate Experience",
    eventName: "Hans Zimmer & Friends: Diamond in the Desert",
    recordedOn: "2025",
    dateLabel: "2025 concert film",
    venue: {
      name: "Multiple locations",
      city: "Dubai",
      country: "United Arab Emirates",
    },
    durationSeconds: 6361,
    source: {
      platform: "youtube",
      videoId: "Lu844oj0fTQ",
      originalUrl: "https://youtu.be/Lu844oj0fTQ?si=RhHIqllUGX7kC8kU",
      uploader: "matogolf",
    },
    description:
      "A feature-length journey through Hans Zimmer's film music, spanning Pirates of the Caribbean, Interstellar, Dune, Inception, and more.",
    recordingNote:
      "This upload is a fan-curated compilation of performances from Hans Zimmer & Friends: Diamond in the Desert, filmed across multiple Dubai locations.",
    setlist: [
      { title: "Pirates of the Caribbean", startAtSeconds: seconds("00:00") },
      { title: "The Dark Knight", startAtSeconds: seconds("13:41") },
      { title: "Interstellar", startAtSeconds: seconds("21:56") },
      { title: "Dune", startAtSeconds: seconds("33:20") },
      { title: "Inception", startAtSeconds: seconds("43:18") },
      { title: "Man of Steel", startAtSeconds: seconds("52:45") },
      { title: "Wonder Woman", startAtSeconds: seconds("1:01:00") },
      { title: "Gladiator", startAtSeconds: seconds("1:10:47") },
      { title: "The Lion King", startAtSeconds: seconds("1:25:48") },
      { title: "Dark Phoenix", startAtSeconds: seconds("1:38:00") },
      { title: "Dunkirk", startAtSeconds: seconds("1:43:29") },
    ],
  },
  {
    id: "rufus-du-sol-live-joshua-tree",
    artistId: "rufus-du-sol",
    title: "Live from Joshua Tree",
    eventName: "Live from Joshua Tree",
    recordedOn: "2019-09",
    dateLabel: "September 2019",
    venue: {
      name: "AWE Ranch",
      city: "Joshua Tree",
      region: "California",
      country: "USA",
    },
    durationSeconds: 2745,
    source: {
      platform: "youtube",
      videoId: "Zy4KtD98S2c",
      originalUrl: "https://youtu.be/Zy4KtD98S2c?si=n1TquWOT50HKbUwB",
      uploader: "RÜFÜS DU SOL",
    },
    description:
      "A seven-song concert film captured at dusk in the quiet expanse of the Southern California desert.",
    setlist: [
      { title: "Valley of the Yuccas", startAtSeconds: seconds("00:04") },
      { title: "Eyes", startAtSeconds: seconds("04:22") },
      { title: "New Sky", startAtSeconds: seconds("08:07") },
      { title: "Desert Night", startAtSeconds: seconds("13:44") },
      { title: "Solace", startAtSeconds: seconds("19:26") },
      { title: "Underwater", startAtSeconds: seconds("24:30") },
      { title: "Innerbloom", startAtSeconds: seconds("30:20") },
    ],
  },
  {
    id: "fred-again-fuji-rock-2025",
    artistId: "fred-again",
    title: "Fuji Rock Festival 2025",
    eventName: "Fuji Rock Festival '25",
    recordedOn: "2025-07-25",
    dateLabel: "July 25, 2025",
    venue: {
      name: "Green Stage, Naeba Ski Resort",
      city: "Yuzawa",
      region: "Niigata",
      country: "Japan",
    },
    durationSeconds: 5439,
    source: {
      platform: "youtube",
      videoId: "nhK3IVpz-wg",
      originalUrl: "https://youtu.be/nhK3IVpz-wg?si=DR7lS8obiAULlory",
      uploader: "randú",
    },
    description:
      "Fred again..'s first performance in Japan, closing Fuji Rock's Green Stage with a 90-minute set.",
    setlist: [
      { title: "Kyle (i found you)" },
      { title: "Bleu (better with time)" },
      { title: "glow / ten" },
      { title: "adore u" },
      { title: "places to be" },
      { title: "Victory Lap", note: "Fred moves to the substage" },
      { title: "Jungle" },
      { title: "Rumble", note: "Skrillex cover" },
      { title: ".nine", note: "Fred returns to the main stage" },
      { title: "peace u need", note: "with Henry Counsell" },
      { title: "Chanel / A New Error / Sabrina (i am a party)" },
      { title: "leavemealone" },
      { title: "Turn On the Lights again.." },
      { title: "Danielle (smile on my face)" },
      { title: "Angie (i've been lost) / Clara (the night is dark)" },
      { title: "Marea (we've lost dancing)" },
      { title: "Billie (loving arms)" },
      { title: "Marco (and everyone) / stayinit" },
      { title: "Delilah (pull me out of this)" },
      { title: "peace u need", note: "Reprise" },
    ],
  },
  {
    id: "odesza-finale-gorge",
    artistId: "odesza",
    title: "The Finale — Live from the Gorge",
    eventName: "The Last Goodbye Finale",
    recordedOn: "2024-07-06",
    dateLabel: "July 6, 2024",
    venue: {
      name: "The Gorge Amphitheatre",
      city: "George",
      region: "Washington",
      country: "USA",
    },
    durationSeconds: 7181,
    source: {
      platform: "youtube",
      videoId: "9s1x9eHoEBE",
      originalUrl: "https://youtu.be/9s1x9eHoEBE?si=zXNOLThSozvDYX4j",
      uploader: "ODESZA",
    },
    description:
      "The final stop of The Last Goodbye tour, performed with drumline, strings, horns, vocalists, and a vast Gorge backdrop.",
    recordingNote:
      "The July 6 encore was cancelled because of a nearby brush fire. This film adds Light of Day and The Last Goodbye from July 5.",
    setlist: [
      { title: "This Version of You", note: "Strings prelude" },
      { title: "Behind the Sun" },
      { title: "Without You (VIP Remix)" },
      { title: "My Friends Never Die" },
      { title: "How Did I Get Here (VIP Remix)" },
      { title: "All We Need (VIP Remix)" },
      { title: "Love Letter / Something About You" },
      { title: "Say My Name / Late Night" },
      { title: "The Loco-Motion (VIP Remix)" },
      { title: "Wide Awake", note: "with Charlie Houston" },
      { title: "One Day They'll Know (VIP Remix)" },
      { title: "Open Wound (Finale Remix)" },
      { title: "If There's Time" },
      { title: "Kusanagi" },
      { title: "Better Now" },
      { title: "Line of Sight" },
      { title: "I Can't Sleep" },
      { title: "North Garden / Healing Grid" },
      { title: "Forgive Me" },
      { title: "HEART ATTACK x In the Rain" },
      { title: "Bloom (VIP Remix)" },
      { title: "Equal / Boy" },
      { title: "Heavier" },
      { title: "TENSE" },
      { title: "KEEP MOVING / BLINE" },
      { title: "Sun Models (VIP Remix)" },
      { title: "Intro (A Moment Apart)" },
      { title: "A Moment Apart / Corners of the Earth" },
      { title: "Across the Room / Falls" },
      { title: "Loyal" },
      { title: "Don't Stop (VIP Remix)" },
      { title: "All My Life", note: "Interlude" },
      { title: "Higher Ground", note: "with Naomi Wild" },
      { title: "It's Only (VIP Remix)" },
      { title: "Light of Day", note: "Encore recorded July 5" },
      { title: "The Last Goodbye", note: "Encore recorded July 5" },
    ],
  },
  {
    id: "armin-van-buuren-best-of-armin-only",
    artistId: "armin-van-buuren",
    title: "The Best of Armin Only",
    eventName: "The Best of Armin Only",
    recordedOn: "2017-05-13",
    dateLabel: "May 13, 2017",
    venue: {
      name: "Johan Cruijff ArenA (then Amsterdam ArenA)",
      city: "Amsterdam",
      country: "Netherlands",
    },
    durationSeconds: 11759,
    source: {
      platform: "youtube",
      videoId: "vDe9pO6P84Q",
      originalUrl: "https://youtu.be/vDe9pO6P84Q?si=f0KGoFuzoIVJwMK6",
      uploader: "Armin van Buuren",
    },
    description:
      "A three-hour arena retrospective celebrating Armin van Buuren's first twenty years in music with guests and live instrumentation.",
    setlist: [
      { title: "Overture (The Best of Armin Only)", startAtSeconds: seconds("00:00:00") },
      { title: "Dark Warrior — Andrew Rayel", startAtSeconds: seconds("00:15:42") },
      { title: "D# Fat — Armin van Buuren & W&W", startAtSeconds: seconds("00:19:20") },
      { title: "Another You", startAtSeconds: seconds("00:21:48") },
      { title: "Make It Right", startAtSeconds: seconds("00:26:20") },
      { title: "Freefall (Manse Remix)", startAtSeconds: seconds("00:30:38") },
      { title: "Panta Rhei", startAtSeconds: seconds("00:33:48") },
      { title: "Heading Up High", startAtSeconds: seconds("00:36:40") },
      { title: "My Symphony", startAtSeconds: seconds("00:41:50") },
      { title: "Arcade — Dimitri Vegas & Like Mike vs W&W", startAtSeconds: seconds("00:47:05") },
      { title: "Xplode", startAtSeconds: seconds("00:51:00") },
      { title: "Strong Ones", startAtSeconds: seconds("00:53:21") },
      { title: "Embargo — Armin van Buuren & Cosmic Gate", startAtSeconds: seconds("00:56:28") },
      { title: "If It Ain't Dutch", startAtSeconds: seconds("01:00:21") },
      { title: "This Is a Test (Arkham Knights Remix)", startAtSeconds: seconds("01:03:50") },
      { title: "Dogs on Acid — Kryder", startAtSeconds: seconds("01:08:50") },
      { title: "This Light Between Us", startAtSeconds: seconds("01:09:38") },
      { title: "Orbion (2017 Revision)", startAtSeconds: seconds("01:14:40") },
      { title: "Shivers (Alex M.O.R.P.H. Red Light Dub)", startAtSeconds: seconds("01:17:20") },
      { title: "This Is What It Feels Like (W&W Remix)", startAtSeconds: seconds("01:21:24") },
      { title: "Sunny Days (Club Mix)", startAtSeconds: seconds("01:28:12") },
      { title: "Off the Hook / Fine Without You", startAtSeconds: seconds("01:32:30") },
      { title: "Adagio for Strings — Mark Sixma", startAtSeconds: seconds("01:37:20") },
      { title: "Turn the Music Up! / Frontera / Waves", startAtSeconds: seconds("01:43:37") },
      { title: "Hyperdrive — Willem de Roo", startAtSeconds: seconds("01:45:42") },
      { title: "Communication (David Gravell Remix)", startAtSeconds: seconds("01:46:40") },
      { title: "In and Out of Love (2017 Revision)", startAtSeconds: seconds("01:49:50") },
      { title: "I Live for That Energy", startAtSeconds: seconds("01:55:07") },
      { title: "I'm in a State of Trance — Ben Gold", startAtSeconds: seconds("01:59:37") },
      { title: "Sail", startAtSeconds: seconds("02:06:55") },
      { title: "Blue Fear", startAtSeconds: seconds("02:11:30") },
      { title: "Serenity", startAtSeconds: seconds("02:15:30") },
      { title: "Alone (Arena Mix)", startAtSeconds: seconds("02:20:30") },
      { title: "Caught in the Slipstream", startAtSeconds: seconds("02:26:47") },
      { title: "Visions — MaRLo", startAtSeconds: seconds("02:32:41") },
      { title: "Again (Alex M.O.R.P.H. Remix)", startAtSeconds: seconds("02:35:47") },
      { title: "Follow Me (Psyburst Mix)", startAtSeconds: seconds("02:39:00") },
      { title: "EIFORYA / Exploration of Space", startAtSeconds: seconds("02:42:15") },
      { title: "Great Spirit", startAtSeconds: seconds("02:44:40") },
      { title: "Dominator (Festival Mix)", startAtSeconds: seconds("02:50:40") },
      { title: "The Ultimate Seduction", startAtSeconds: seconds("02:54:40") },
      { title: "Ping Pong (Arena Mix)", startAtSeconds: seconds("02:57:52") },
      { title: "Looking for Your Name", startAtSeconds: seconds("03:06:07") },
    ],
  },
  {
    id: "dj-m-zone-doncaster-warehouse-1992",
    artistId: "dj-m-zone",
    title: "Doncaster Warehouse 1992",
    eventName: "Doncaster Warehouse",
    recordedOn: "1992",
    dateLabel: "1992",
    venue: {
      name: "Doncaster Warehouse",
      city: "Doncaster",
      region: "South Yorkshire",
      country: "United Kingdom",
    },
    durationSeconds: 9282,
    source: {
      platform: "youtube",
      videoId: "lIsZVlbasiA",
      originalUrl: "https://www.youtube.com/watch?v=lIsZVlbasiA",
      uploader: "DJ M-Zone",
    },
    description:
      "Raw footage from three 1992 nights at Doncaster Warehouse, moving through piano house, hardcore, jungle, hoover, and techno.",
    recordingNote:
      "This edit combines footage from three separate nights. The source does not provide a verified tracklist.",
  },
  {
    id: "marilyn-manson-bizarre-festival-1997",
    artistId: "marilyn-manson",
    title: "Live at Bizarre Festival",
    eventName: "Bizarre Festival",
    recordedOn: "1997-08-16",
    dateLabel: "August 16, 1997",
    venue: {
      name: "Butzweilerhof",
      city: "Cologne",
      country: "Germany",
    },
    durationSeconds: 2250,
    source: {
      platform: "youtube",
      videoId: "ap5VXO983WM",
      originalUrl: "https://www.youtube.com/watch?v=ap5VXO983WM",
      uploader: "Marilyn666Manson",
    },
    description:
      "A nine-song festival set from the Dead to the World tour, captured at the Butzweilerhof grounds during the 1997 Bizarre Festival.",
    recordingNote:
      "The event listing and Rockpalast archive place this performance on August 16, 1997; the submitted July 21 date was corrected.",
    setlist: [
      { title: "Intro", startAtSeconds: seconds("00:00") },
      { title: "Angel With the Scabbed Wings", startAtSeconds: seconds("02:40") },
      { title: "Get Your Gunn", startAtSeconds: seconds("05:56") },
      { title: "Cake and Sodomy", startAtSeconds: seconds("09:09") },
      { title: "Dried Up, Tied and Dead to the World", startAtSeconds: seconds("13:04") },
      { title: "Tourniquet", startAtSeconds: seconds("18:00") },
      { title: "Lunchbox", startAtSeconds: seconds("22:18") },
      { title: "Sweet Dreams (Are Made of This)", startAtSeconds: seconds("27:21") },
      { title: "The Beautiful People", startAtSeconds: seconds("32:08") },
      { title: "Irresponsible Hate Anthem", startAtSeconds: seconds("36:35") },
    ],
  },
]
